# -*- coding: UTF-8 -*-
"""Shared data for set 7 exercises."""

# Sample pet data used across all exercises
pets = [
    "dog",
    "goat",
    "pig",
    "sheep",
    "cattle",
    "zebu",
    "cat",
    "chicken",
    "guinea pig",
    "donkey",
    "duck",
    "water buffalo",
    "western honey bee",
    "dromedary camel",
    "horse",
    "silkmoth",
    "pigeon",
    "goose",
    "yak",
    "bactrian camel",
    "llama",
    "alpaca",
    "guineafowl",
    "ferret",
    "muscovy duck",
    "barbary dove",
    "bali cattle",
    "gayal",
    "turkey",
    "goldfish",
    "rabbit",
    "koi",
    "canary",
    "society finch",
    "fancy mouse",
    "siamese fighting fish",
    "fancy rat and lab rat",
    "mink",
    "red fox",
    "hedgehog",
    "guppy",
]
